[support]
musicclass=default
strategy=ringall
timeout=15
retry=5
maxlen=0
joinempty=yes
leavewhenempty=no

member => SIP/1001
member => SIP/1002

[sales]
musicclass=default
strategy=leastrecent
timeout=15
retry=5
maxlen=0

member => SIP/2001
